# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('literature', models.CharField(blank=True, max_length=255, null=True)),
                ('meetingname', models.CharField(blank=True, db_column='meetingName', max_length=255, null=True)),
                ('meetingtime', models.CharField(blank=True, db_column='meetingTime', max_length=255, null=True)),
                ('meetingadress', models.CharField(blank=True, db_column='meetingAdress', max_length=255, null=True)),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=15, null=True)),
                ('classnumber', models.CharField(blank=True, db_column='classNumber', max_length=25, null=True)),
                ('publishtime', models.CharField(blank=True, db_column='publishTime', max_length=125, null=True)),
                ('pagenumber', models.CharField(blank=True, db_column='pageNumber', max_length=255, null=True)),
                ('searchkey', models.CharField(blank=True, db_column='searchKey', max_length=125, null=True)),
                ('searchtype', models.CharField(blank=True, db_column='searchType', max_length=125, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'conference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('degreeunit', models.CharField(blank=True, db_column='degreeUnit', max_length=255, null=True)),
                ('awardedthedegree', models.CharField(blank=True, db_column='awardedTheDegree', max_length=255, null=True)),
                ('professional', models.CharField(blank=True, max_length=255, null=True)),
                ('mentorname', models.CharField(blank=True, db_column='mentorName', max_length=255, null=True)),
                ('degreeinannual', models.CharField(blank=True, db_column='degreeInAnnual', max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=50, null=True)),
                ('classnumber', models.CharField(blank=True, db_column='classNumber', max_length=60, null=True)),
                ('publishtime', models.CharField(blank=True, db_column='publishTime', max_length=25, null=True)),
                ('searchkey', models.CharField(blank=True, db_column='searchKey', max_length=25, null=True)),
                ('searchtype', models.CharField(blank=True, db_column='searchType', max_length=55, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'degree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('englishtitle', models.CharField(blank=True, db_column='englishTitle', max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('englishkeywords', models.CharField(blank=True, db_column='englishKeyWords', max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=125, null=True)),
                ('englishauthors', models.CharField(blank=True, db_column='englishAuthors', max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=75, null=True)),
                ('journalname', models.CharField(blank=True, db_column='journalName', max_length=255, null=True)),
                ('journal', models.CharField(blank=True, max_length=255, null=True)),
                ('yearsinfo', models.CharField(blank=True, db_column='yearsInfo', max_length=50, null=True)),
                ('journalsection', models.CharField(blank=True, db_column='journalSection', max_length=255, null=True)),
                ('classnumber', models.CharField(blank=True, db_column='classNumber', max_length=25, null=True)),
                ('fundprogram', models.CharField(blank=True, db_column='fundProgram', max_length=125, null=True)),
                ('publishtime', models.CharField(blank=True, db_column='publishTime', max_length=25, null=True)),
                ('pages', models.CharField(blank=True, max_length=6, null=True)),
                ('pagenumber', models.CharField(blank=True, db_column='pageNumber', max_length=6, null=True)),
                ('searchkey', models.CharField(blank=True, db_column='searchKey', max_length=50, null=True)),
                ('searchtype', models.CharField(blank=True, db_column='searchType', max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'perio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('englishtitle', models.CharField(blank=True, db_column='englishTitle', max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('reporttype', models.CharField(blank=True, db_column='reportType', max_length=255, null=True)),
                ('openrange', models.CharField(blank=True, db_column='openRange', max_length=125, null=True)),
                ('pagenumber', models.CharField(blank=True, db_column='pageNumber', max_length=25, null=True)),
                ('projectname', models.CharField(blank=True, db_column='projectName', max_length=125, null=True)),
                ('planname', models.CharField(blank=True, db_column='planName', max_length=125, null=True)),
                ('compiletime', models.CharField(blank=True, db_column='compileTime', max_length=125, null=True)),
                ('approvalyear', models.CharField(blank=True, db_column='approvalYear', max_length=125, null=True)),
                ('collection', models.CharField(blank=True, max_length=125, null=True)),
                ('searchkey', models.CharField(blank=True, db_column='searchKey', max_length=125, null=True)),
                ('searchtype', models.CharField(blank=True, db_column='searchType', max_length=125, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tech',
                'managed': False,
            },
        ),
    ]
