# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lianjiaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('reddess', models.CharField(blank=True, max_length=255, null=True)),
                ('acreage', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('gzrs', models.CharField(blank=True, max_length=255, null=True)),
                ('liulanshu', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=255, null=True)),
                ('urls', models.CharField(blank=True, max_length=255, null=True)),
                ('chaoxiang', models.CharField(blank=True, max_length=255, null=True)),
                ('geju', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lianjiaA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lianjiab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, max_length=255, null=True)),
                ('louceng', models.CharField(blank=True, max_length=255, null=True)),
                ('mianji', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('jieguo', models.CharField(blank=True, max_length=255, null=True)),
                ('taofang_mianji', models.CharField(blank=True, max_length=255, null=True)),
                ('jianzhu_leixing', models.CharField(blank=True, max_length=255, null=True)),
                ('jianzhu_chaoxiang', models.CharField(blank=True, max_length=255, null=True)),
                ('jianzhu_jiegou', models.CharField(blank=True, max_length=255, null=True)),
                ('jianzhu_xiushan', models.CharField(blank=True, max_length=255, null=True)),
                ('jianzhu_tihu', models.CharField(blank=True, max_length=255, null=True)),
                ('jianzhu_gongnuan', models.CharField(blank=True, max_length=255, null=True)),
                ('jianzhu_dianti', models.CharField(blank=True, max_length=255, null=True)),
                ('jianzhu_nianxian', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('reddesss', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('guapai_time', models.CharField(blank=True, max_length=255, null=True)),
                ('jiaoyi_shuxing', models.CharField(blank=True, max_length=255, null=True)),
                ('shang_time', models.CharField(blank=True, max_length=255, null=True)),
                ('yongtu', models.CharField(blank=True, max_length=255, null=True)),
                ('nianxian', models.CharField(blank=True, max_length=255, null=True)),
                ('chanquan_suoyou', models.CharField(blank=True, max_length=255, null=True)),
                ('diya', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lianjiaB',
                'managed': False,
            },
        ),
    ]
